# General
name: RoDI
description: Robot Didáctico Inalámbrico
url: http://rodibot.github.io

markdown: redcarpet
highlighter: pygments

paginate: 10
permalink: /:title

# Social share and comments.
#disqus-id:
#twitter:
#github:
#google:

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
